language: node_js

node_js: 8

install:
  - npm ci

script:
  - npm run lint
  - npm run test
  - npm run compile

deploy:
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      tags: true
      repo: sparkplug/momoapi-node
      branch: master

  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "lib/*"
    skip_cleanup: true
    on:
      tags: true
      repo: sparkplug/momoapi-node
      branch: master
